# Numpy

In [1]:
import numpy as np

In [2]:
# Few important function in numpy

In [3]:
a = np.array([1, 3, 5, 7])

In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
a.shape

(4,)

In [6]:
b = np.array([[1, 3, 4, 6],[3,4,5,6]])

In [7]:
b.shape

(2, 4)

In [8]:
np.dot(b,b.T)  # dot product of two arrays

array([[62, 71],
       [71, 86]])

In [18]:
np.random.randint(60, 100, 10)


array([65, 71, 85, 82, 90, 87, 77, 69, 90, 60])

In [20]:
matrix = np.random.randint(60, 100, (5,5))

In [21]:
matrix

array([[62, 68, 76, 63, 71],
       [89, 96, 80, 63, 88],
       [74, 95, 84, 68, 96],
       [89, 89, 88, 64, 62],
       [96, 93, 92, 67, 71]])

In [22]:
np.max(matrix)  #max element

96

In [23]:
np.min(matrix) # min element

62

In [28]:
a = np.array([1, 3, 8, 1, 6, 6, 6, 6, 11, 3])

In [29]:
np.argmax(a)  # return index of the largest element

8

In [30]:
np.argmin(a)  # index where the smallest element is appearing

0

In [43]:
# unique values present in the array
b = np.unique(a, return_index = True, return_counts=True,)
b

(array([ 1,  3,  6,  8, 11]),
 array([0, 1, 4, 2, 8], dtype=int64),
 array([2, 2, 4, 1, 1], dtype=int64))

In [50]:
# to find the element with the highest frequency
indx = np.argmax(b[2])  # return index of element with highest frequency
result = b[0][indx]  # to fetch the element from b which has 3 elements
result

6

In [51]:
# slicing in the array(1D, 2D, 3D)

matrix

array([[62, 68, 76, 63, 71],
       [89, 96, 80, 63, 88],
       [74, 95, 84, 68, 96],
       [89, 89, 88, 64, 62],
       [96, 93, 92, 67, 71]])

In [52]:
# extract element from row 2,3 and coulumn 1,2

matrix[2:4, 1:3]

array([[95, 84],
       [89, 88]])